services:
  nuxt-app:
    image: node:18-bullseye
    container_name: nuxt
    working_dir: /src
    volumes:
      - .:/src
      #- /app/.nuxt
      - /src/.git
      - /src/.output
      - /app/.pnpm-store
    command: bash -c "pwd && ls -la && echo 'INI' && npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
